[graveSettings]
generateGraves = true
retrievalType = "ON_BREAK"
dropType = "ON_GROUND"
dropPlayerHead = false
dropGraveBlock = false
requireGraveItem = false
generateEmptyGraves = false
ignoreSpawnProtection = true
deathInSpawnProtection = "CREATE_GRAVE"
priority = "GRAVE"
unlockableGraves = false
deleteEnchantments = ["minecraft:vanishing_curse"]
soulboundEnchantments = ["yigd:soulbound"]
applyBindingCurse = true
trySoft = true
tryStrict = true
replaceWhenClaimed = true
blacklistDimensions = []
graveInVoid = false
ignoreDeathTypes = []
graveSpawnHeight = 2
lastResort = "SET_GRAVE"
putXpInGrave = false
defaultXpDrop = false
xpDropPercent = 60
tellDeathPos = false
maxGraveBackups = 50

[graveSettings.graveRobbing]
enableRobbing = true
onlyMurderer = false
afterTime = 1
timeType = "SECONDS"
robPriority = "INVENTORY"

[graveSettings.graveDeletion]
canDelete = false
afterTime = 1
timeType = "HOURS"
dropInventory = false

[graveSettings.itemLoss]
enableLoss = false
ignoreSoulboundItems = true
affectStacks = false
usePercentRange = false
lossRangeFrom = 0
lossRangeTo = 5
percentChanceOfLoss = 100

[graveSettings.blockUnderGrave]
generateBlockUnder = true
inOverWorld = "minecraft:cobblestone"
inNether = "minecraft:soul_soil"
inTheEnd = "minecraft:end_stone"
inCustom = "minecraft:dirt"

[graveSettings.graveCompatConfig]
levelzXpInGraves = true
levelzXpDropPercent = 100
claimRuleOverride = "CREATE_GRAVE"

[graveSettings.graveRenderSettings]
useRenderFeatures = true
renderGraveSkull = true
renderGraveOwner = true
textShadow = false
adaptRenderer = true
glowingGrave = true
glowMinDistance = 0
glowMaxDistance = 8
[utilitySettings]
soulboundEnchant = false
deathSightEnchant = false

[utilitySettings.scrollItem]
scrollType = "DISABLED"
retrieveOnRespawn = true

[utilitySettings.graveKeySettings]
enableKeys = false
alwaysRequire = false
retrieveOnRespawn = true
getFromGui = false
rebindable = false
graveKeySpecification = "PLAYER"
[commandToggles]
coreCommandName = "yigd"
retrieveGrave = true
robGrave = true
selfView = true
adminView = true
moderateGraves = true
clearGraveBackups = true
whitelist = true
whitelistAdd = true
whitelistRemove = true
whitelistToggle = true
